import {escapeHtml as esc} from './html';
import {localRequest} from './source-import';
import type {Track} from './album-player';
type Item={bvid:string;title:string;artist:string;cover?:string;available:boolean};
type Part={cid:number;page:number;title:string;duration:number};
export class BiliFavorites {
 private dialog=document.createElement('dialog');private busy=false;private stopped=false;private job?:string;
 private id='';private title='B 站收藏夹';private artist='';private page=0;private more=false;
 private items:Item[]=[];private selected=new Map<string,{item:Item;part:Part}>();private completed=new Map<string,Track>();
 constructor(private save:(album:{title:string;artist:string;tracks:Track[]})=>Promise<void>){
 this.dialog.className='album-import source-import';this.dialog.innerHTML=`<header><span>BILIBILI / 收藏夹</span><button data-fav="close" aria-label="关闭">×</button></header><h2>从收藏夹里选歌。</h2><p>粘贴公开收藏夹链接或收藏夹 ID。展开视频后可选择多个分 P，下载音频后加入同一歌单。</p><label>收藏夹链接<input id="fav-link" placeholder="https://space.bilibili.com/…/favlist?fid=…"></label><button data-fav="read" class="solid-button">读取收藏夹 →</button><h3 id="fav-title"></h3><div id="fav-items"></div><button data-fav="more" hidden>加载更多</button><p id="fav-count">已选 0 首</p><label>音质<select id="fav-quality"><option value="auto">自动 · 最高可用</option><option value="30280">高音质</option><option value="30232">标准音质</option><option value="30216">流畅音质</option></select></label><small>以平台实际返回的音轨为准。</small><button data-fav="import" class="solid-button">下载所选音频并导入</button><button data-fav="stop" hidden>停止下载</button><p class="source-status" role="status"></p>`;
 document.body.append(this.dialog);this.dialog.addEventListener('close',()=>this.dialog.remove());this.dialog.addEventListener('cancel',e=>{if(this.busy)e.preventDefault()});
 this.dialog.addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!b)return;const action=b.dataset.fav;if(action==='stop'){this.stopped=true;if(this.job)void localRequest('cancel',{id:this.job}).catch(()=>{});return;}if(this.busy)return;if(action==='close')this.dialog.close();if(action==='read')void this.read(false);if(action==='more')void this.read(true);if(action==='parts')void this.parts(Number(b.dataset.index));if(action==='import')void this.import();});
 this.dialog.addEventListener('change',e=>{const input=e.target as HTMLInputElement;if(!input.dataset.key)return;const part=JSON.parse(input.dataset.part!) as Part,item=this.items[Number(input.dataset.item)];if(input.checked)this.selected.set(input.dataset.key,{item,part});else this.selected.delete(input.dataset.key);this.dialog.querySelector('#fav-count')!.textContent=`已选 ${this.selected.size} 首`;});
 }
 open(){this.dialog.showModal()}
 private status(text:string){this.dialog.querySelector('.source-status')!.textContent=text}
 private lock(busy:boolean){this.busy=busy;this.dialog.querySelectorAll<HTMLInputElement>('button,input,select').forEach(b=>b.disabled=busy&&b.dataset.fav!=='stop');this.dialog.querySelector<HTMLButtonElement>('[data-fav=stop]')!.hidden=!busy;}
 private async read(append:boolean){this.lock(true);this.status('正在读取收藏夹…');try{const result=await localRequest('bili-favorites',{link:append?this.id:this.dialog.querySelector<HTMLInputElement>('#fav-link')!.value,page:append?this.page+1:1});if(!append){this.items=[];this.selected.clear();this.completed.clear();this.dialog.querySelector('#fav-items')!.innerHTML='';this.dialog.querySelector('#fav-count')!.textContent='已选 0 首';}this.id=result.id;this.title=result.title;this.artist=result.artist;this.page=result.page;this.more=result.hasMore;
 this.dialog.querySelector('#fav-title')!.textContent=`${this.title} · ${result.total} 个收藏`;
 for(const item of result.items as Item[]){if(item.bvid&&this.items.some(t=>t.bvid===item.bvid))continue;const index=this.items.push(item)-1;this.dialog.querySelector('#fav-items')!.insertAdjacentHTML('beforeend',`<div class="fav-item"><strong>${esc(item.title)}</strong><small>${esc(item.artist)}</small>${item.available?`<button data-fav="parts" data-index="${index}">选择音频 / 分 P</button>`:'<small>已失效或暂不支持的内容</small>'}<div id="fav-parts-${index}"></div></div>`);}
 this.dialog.querySelector<HTMLButtonElement>('[data-fav=more]')!.hidden=!this.more;this.status(this.items.length?'展开视频并勾选需要的音频。':'收藏夹为空。');}catch(e){this.status((e as Error).message)}finally{this.lock(false)}}
 private async parts(index:number){const container=this.dialog.querySelector(`#fav-parts-${index}`)!;if(container.childElementCount)return;this.lock(true);try{const item=this.items[index],video=await localRequest('video',{link:'https://www.bilibili.com/video/'+item.bvid});container.innerHTML=(video.pages as Part[]).map(part=>`<label><input type="checkbox" data-key="${item.bvid}:${part.cid}" data-item="${index}" data-part="${esc(JSON.stringify(part))}">P${part.page} · ${esc(part.title)} · ${Math.round(part.duration/60)} 分钟</label>`).join('');this.status('勾选分 P，可继续选择其他视频。')}catch(e){this.status((e as Error).message)}finally{this.lock(false)}}
 private async import(){if(!this.selected.size){this.status('请先选择至少一首音频。');return;}this.lock(true);this.stopped=false;const quality=this.dialog.querySelector<HTMLSelectElement>('#fav-quality')!.value;const failures:string[]=[];
 try{let n=0;for(const [key,{item,part}] of this.selected){if(this.stopped)break;n++;if(this.completed.has(key))continue;try{this.status(`正在下载 ${n} / ${this.selected.size}：${item.title} · ${part.title}`);let j=await localRequest('download',{bvid:item.bvid,cid:part.cid,quality});this.job=j.id;if(this.stopped)await localRequest('cancel',{id:j.id});while(['queued','resolving','downloading'].includes(j.state)){await new Promise(r=>setTimeout(r,700));j=await localRequest('jobs/'+j.id);}if(j.state!=='complete')throw Error(j.error??'下载取消');const response=await fetch(j.file);if(!response.ok)throw Error('音频读取失败');this.completed.set(key,{title:j.title,artist:j.artist,file:await response.blob(),cover:item.cover,duration:j.duration,quality:j.quality,source:`https://www.bilibili.com/video/${item.bvid}?p=${part.page}`});}catch(e){failures.push(item.title+'：'+(e as Error).message)}finally{this.job=undefined}}
 const tracks=[...this.selected.keys()].flatMap(key=>this.completed.has(key)?[this.completed.get(key)!]:[]);if(tracks.length){await this.save({title:this.title,artist:this.artist,tracks});for(const key of [...this.selected.keys()])if(this.completed.has(key)){this.selected.delete(key);this.completed.delete(key);const input=this.dialog.querySelector<HTMLInputElement>(`[data-key="${key}"]`);if(input)input.checked=false;}}
 this.dialog.querySelector('#fav-count')!.textContent=`已选 ${this.selected.size} 首`;this.status(`已导入 ${tracks.length} 首。${this.stopped?'已停止，保留已完成的音频。':''}${failures.length?'未完成的仍保留勾选，可重试。'+failures.join('；'):''}`);
 }catch(e){this.status('保存失败，已下载音频保留在此窗口，可再次点击导入。'+(e as Error).message)}finally{this.lock(false)}}
}
